### ISSUE TITLE
Allow full import from Google Contacts

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-vcard#10]
Here is a gist of a contact that has every fields of a Google contact:

https://gist.github.com/hansbkk/b28f3bbb97b50c0275bd

Thank you @hansbkk for providing us this complete VCard!

**Comment by hansbkk** [comment]
Thanks Frank

Note that Google is likely to add support for fields like "company / title / role", "categories / groups" in the future, or make changes to match any made by Apple (hopefully towards greater compliance with more open standards)

So this sort of test should be done periodically to see what changes need to be made to keep Cozy "in sync" with these two 800-lb gorillas.

FFR to incoming googlers: more general issue here: https://github.com/cozy/cozy-sync/issues/26

**Comment by hansbkk** [comment]
Don't know what role this file plays in the project

https://github.com/cozy/cozy-vcard/blob/master/test/google.vcf

but perhaps it should be a more complete example. . .

**Comment by frankrousseau** [comment]
Yes this is the example us by our automatic tests. We should add stuff to it.

**Comment by hansbkk** [comment]
Result of doing the same with SabreDAV on fruux.com. Bottom "before" one is a fresh creation using all fields in their contact editor, top "after" is the result of importing it into Google contacts.

https://gist.github.com/hansbkk/8430b84759ee8b7a1e83

NOt that Google doesn't support the "ShowAs" company feature, but otherwise the only other changes to the data itself is minor case-changes.

Oh and the "compound type" issue with "Home fax" mentioned earlier.

So I think Cozy is on the right track using tools that follow the SabreDAV model. Just that work needs to be done to make it support the various extensions better, and of course ensure if possible that unrecognized lines/field labels aren't dropped.

**Comment by frankrousseau** [comment]
@hansbkk  I'm working on the import. It looks like we don't handle properly many vcard fields. It will take much more time than I thought to fix. We will keep you inform on this issue.

**Comment by hansbkk** [comment]
Thanks I realize it's a large and messy undertaking.

I realize your architectural choices may make this idea difficult, but IMO as a layman, the initial parsing should pull in all fields properly recognized, and then have a generic notes-type "other-data" text field for the rest (unrecognized fields), and when outputting, go ahead and append it back to the end of the "known parsed" vCard data.

**Comment by frankrousseau** [comment]
Hello @hansbkk,

 Could you try again? We improved the import step. It should work better. Could you update your contact application and try again?

We are still working on the export and and sync steps.
