### ISSUE TITLE
Unsupported field "type" of property TEL

### ISSUE THREAD

**Issue by jsilvestre** [cozy/cozy-vcard#7]
As reported by @hansbkk

 >In the Google interface, there is a pre-defined pair of strings "Home fax" and "Work fax", which get exported as follows in the vCard:

> TEL;TYPE=WORK;TYPE=FAX:212 555 2345
TEL;TYPE=HOME;TYPE=FAX:212 555 3456

> These both show up in Cozy as "FAX" alone, so it is impossible to tell which is the home fax number and which is the work number.

> My work-around solution for now is to enter these as a custom string rather than using Google's predefined labels, which will export as:

> item1.TEL:212 555 2345
item1.X-ABLabel:Work Fax

> and this works fine, but obviously it isn't ideal to require the user to have to remember which google labels work with Cozy and which don't.

**Comment by hansbkk** [comment]
I've found other clients rather than use:

TEL;TYPE=WORK;TYPE=FAX:212 555 2345
TEL;TYPE=HOME;TYPE=FAX:212 555 3456

they do "compound types" like this:

TEL;TYPE=WORK,FAX:212 555 2345
TEL;TYPE=HOME,FAX:212 555 3456

and then display as "Work fax" and "Home fax"

Not sure which is more "correct". If we transform into the latter, test to see if Google's import interprets it correctly?

**Comment by frankrousseau** [comment]
It should work fine now.
